### ISSUE TITLE
Dependency Conflict

### ISSUE THREAD

**Issue by NirKosti** [BSAkash/IG-SRL#3]
Hi,

After running the following commands:

```python
!git clone https://github.com/BSAkash/NLP4GOV
%cd NLP4GOV/src
!pip install -q -r ./constituent_coreferences/requirements.txt
from constituent_coreferences import corefs
%cd /content/
```
I encountered an issue at the line:
```python
from constituent_coreferences import corefs
```
The error message is:
```plaintext
ModuleNotFoundError: No module named 'huggingface_hub.serialization'
```
I updated huggingface-hub, but it seems like requirements.txt installs an older version via one of the other dependencies. It might help to update the requirements.txt file in the repository to resolve this conflict. If there's another solution, any assistance would be much appreciated.

Thank you!

**Comment by enfascination** [comment]
Hello @NirKosti !  First, is this a local install or via colab? Are you able to get the notebook working from within colab?

**Comment by NirKosti** [comment]
Hi @enfascination, I am using Colab, not my local installation.

**Comment by Mahasweta-usc** [comment]
Thanks for bringing this to attention. Yes, the dependency resolver does run into trouble because one of the libraries (AllenNLP) is now legacy and also somewhat ambiguous on version upper bounds. I will add a hard pip install --upgrade huggingface-hub to the notebook. Please keep us posted on other issues so we can fix them as you go along

**Comment by NirKosti** [comment]
Thank you, @Mahasweta-usc. I am still encountering an issue with huggingface_hub. I ran this again:
```
!git clone https://github.com/BSAkash/NLP4GOV #cloning the github repo, you can visit this url for the entire directory
%cd NLP4GOV/src
!pip install -q -r ./constituent_coreferences/requirements.txt # installs all required dependencies in one go!
from constituent_coreferences import corefs
%cd /content/
```

I got the error message:
```
ImportError: cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' (/usr/local/lib/python3.10/dist-packages/huggingface_hub/__init__.py)
```

This error occurs at the same point in the code:
```
from constituent_coreferences import corefs
```

Could you please assist in resolving this issue?

**Comment by Mahasweta-usc** [comment]
You will still need to pull the master for the new changes to reflect. You will know it has worked when the updated cell looks like:
https://github.com/Mahasweta-usc/NLP4GOV/blob/master/Policy%20Toolkits/ABDICO_coreferences.ipynb

https://docs.github.com/en/get-started/using-git/getting-changes-from-a-remote-repository
